services:
  node1:
    build: ./node
    container_name: node1
    environment:
      - NODE_PORT=8000
      - NODE_HOST=http://node1:8000
      - NODE_NAME=node1
      - MINER=1
      - MINER_ADDRESS=jwZtUCadJT6649dmzbHTnRoNjth9HsPC
      # Password = 1234 --path /root/.simplechain/miner1.json
    ports:
      - "8001:8000"
    networks:
      - chainnet
    volumes:
      - node1_data:/data

  node2:
    build: ./node
    container_name: node2
    environment:
      - NODE_PORT=8000
      - NODE_HOST=http://node2:8000
      - NODE_NAME=node2
      - MINER=1
      - MINER_ADDRESS=UgLwGGXDzw2x9BWy7tDexk2MYNA5HSxu
      # Password = 1234 --path /root/.simplechain/user1.json
    ports:
      - "8002:8000"
    networks:
      - chainnet
    volumes:
      - node2_data:/data

  node3:
    build: ./node
    container_name: node3
    environment:
      - NODE_PORT=8000
      - NODE_HOST=http://node3:8000
      - NODE_NAME=node3
      - MINER=0
      - MALICIOUS=0
      - MINER_ADDRESS=LTJiPfAZZjRBLQic5QCvFQpqUKXTPu6M
      # Password = 1234 --path /root/.simplechain/user2.json
    ports:
      - "8003:8000"
    networks:
      - chainnet
    volumes:
      - node3_data:/data

  wallet:
    build: ./wallet
    container_name: wallet
    stdin_open: true
    tty: true
    networks:
      - chainnet
    volumes:
      - wallet_data:/root/.simplechain

networks:
  chainnet:
    driver: bridge

volumes:
  node1_data:
  node2_data:
  node3_data:
  wallet_data: